spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: liveklass
  datasource:
    url: jdbc:mysql://mysql:3306/liveklass?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app